name: Test Github Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21.0.6
        java-package: jdk
        check-latest: false
        distribution: adopt
    - name: Run with Java
      run:
       java Trial
